---
# zypper_ref_accept_key/tasks/main.yml

- name: "Refresh all repos and accept all unknown GPG keys"
  community.general.zypper_repository:
    repo: '*'
    runrefresh: true
    auto_import_keys: true
  when: 'ansible_os_family == "Suse" or ansible_os_family == "openSUSE Leap"'
