---
# zypper_ref_accept_key/tasks/main.yml

- name: "Refresh all repos and accept all unknown GPG keys"
  zypper_repository:
    repo: '*'
    runrefresh: yes
    auto_import_keys: yes
  when: 'ansible_os_family == "Suse" or ansible_os_family == "openSUSE Leap"'
